spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_management_njupt?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: lsj666666
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: hotel-management-system

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true